### ISSUE TITLE
Maximum MP Score problem. (In the latest beta version)

### ISSUE THREAD

**Issue by slottwo** [League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima#117]
**Bug Description:**
The calculation of maximum Mind Point is not including the character's level in the sum as it should (visit the core rulebook on page 163: _"Your maximum Mind Points are equal to your total character level + five times your character’s base Willpower die size."_)

**Steps to Reproduce:**
1. At version [2.3.7-beta.2](https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima/releases/tag/2.3.7-beta.2)
2. Navigate to 'Actors tab'
3. Click on 'Create Actor'
4. Click on 'Create New Actor'
5. Observe the error occurring: Note that the maximum HP is valued at 45 (5*8+5), but the maximum MP is only 40.
6. Change the Level to '6'
7. Observe the error occurring: See that the maximum HP has increased to 46 (5*8+6), but the maximum MP remains 40.

**Expected behavior:**
I expected that at points 4 and 6 the maximum MP score would be evaluated as 45 and 46, respectively.

**Attachments:**
![image](https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima/assets/41028091/61759a80-5a1a-48f1-b3d4-2502ecc645e5)

**Comment by spyrella** [comment]
The issue has been addressed in the development branch. It will be available on the new prelease beta, probably by tonight.

**Comment by spyrella** [comment]
Is available with the new V2.3.7 dropping tonight.
