### ISSUE TITLE
Armors without Stat

### ISSUE THREAD

**Issue by Dex10k** [League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima#121]
When using equipping an armor onto a Player such as steel plate or Runic Plate that should not have an attribute increase if the settings are set to not add a stat, it defaults to adding dexterity. This leads to ridiculous defense values.
![image](https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima/assets/47685116/8f98b5ce-f72a-4f0e-b2f8-61bc24648a5a)

Edit: This issue disappears if they're marked Martial, but could affect Rare armors

**Comment by spyrella** [comment]
You are correct, whether it becomes 12 DEF or DEF+12 is if martial is checked. It was an afterthought that, martial can be changed via rare armor, so we'd have to figure out a way to account for that. Thanks.

**Comment by Shourn** [comment]
This appears to have been fixed in the meantime.
If you can still reproduce the problem with a current version of the system please reopen the issue.
