### ISSUE TITLE
Pronouns field on NPC sheet doesn't save

### ISSUE THREAD

**Issue by chaoscontrolled123** [League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima#128]
**Bug Description:**
I noticed that the pronouns field on the NPC sheet wasn't saving when I edited it, so I exported the data for the actor and searched the JSON-- it looks like NPCs don't have a key/value pair for this field at all. It would be nice to have!

**Steps to Reproduce:**
1. Create NPC actor
2. Fill out pronouns field
3. Close sheet, or edit sheet settings
4. Reopen sheet
5. Field is empty

**Expected behavior:**
The pronouns field persists after closing the sheet.

(Thanks for all your hard work on this system! I'm excited to be running my first game 😁)

**Comment by Shourn** [comment]
Added field for NPC pronouns, so they can get saved.
Fixed in next release.
