### ISSUE TITLE
Use alternative image rendering algorithm for pixel art

### ISSUE THREAD

**Issue by profounddark** [League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima#129]
**User Story:**
As a GM, I want low-resolution pixel art that I use for Items, Abilities, etc. to to maintain the pixelated edges.

**Additional context:**
The Fabula Ultima rulebook features low res pixel art for Weapons and Equipment. Similar images can be found online, often in the style of old JRPGs. When the image is set for an Item (i.e., Spell, Weapon, etc.), the default image rendering algorithm uses a method that, while good for normal images, tends to make pixel art look like blurry mess.

Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering

**Comment by spyrella** [comment]
There are two workarounds for this:

1. Manually up scaling images to a higher resolution (256x256)
- If you're in the roostergames discord this link takes you to a script that converts and upscales your pixel art (https://discord.com/channels/447159961491865610/1034111889740943470/1235182372950114435)

2. Download the [Custom CSS](https://foundryvtt.com/packages/custom-css/) module and apply the following to global css styles
```
.sheet-header .profile-img {
image-rendering: pixelated;
}

.chat-message .message-header .title-desc img, .chat-message.whisper .message-header .title-desc img {
image-rendering: pixelated;
} 

.directory .directory-item img {
image-rendering: pixelated;
}

.directory-list .thumbnail {
    image-rendering: pixelated;
}
```
Link to the tutorial if you're in the roostergames discord (https://discord.com/channels/447159961491865610/1034111889740943470/1205011268575035452)

3. The game setting "Pixelated View" is kinda broken, might be fixed or removed at a later update.
