### ISSUE TITLE
Magic Checks for Spells on NPC sheets display the wrong Attribution combination, but use the correct one.

### ISSUE THREAD

**Issue by Melarith** [League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima#130]
**Bug Description:**
When you create a spell for an NPC, it will display the Magic Check for it as using INS + MIG, no matter what Attributes the Magic Check actually uses. This is a bigger annoyance than I first thought, since it will show the incorrect information to players when using the automated Study function.

**Steps to Reproduce:**
1. Create a new spell on an NPC sheet.
2. Favorite it and expand the tooltip, or Survey it.
3. You'll see it shows INS + MIG, even if you changed it from its default.

**Expected behavior:**
The NPC sheets should display the Attribute combination they actually use for Magic Checks.

**Attachments (if applicable):**
Here's an example: this Cactitan uses INS + WLP for its Noxious Thorns spell, but the Study result says otherwise, accidentally tricking my players into making a tactical blunder that nearly got one of them killed. Oops!
<img width="388" alt="Cactitan" src="https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima/assets/12849116/730d455d-8b27-4ca0-a09b-f3dac46d3c0e">

**Comment by iamthetot** [comment]
Doesn't seem to be specific to NPC sheets. It's occurring on my PCs' sheets as well.

**Comment by Themko30** [comment]
Also for the PC it's always MIG + MIG no matter what.

**Comment by Shourn** [comment]
Turns out that the internal data structures for spells are unlike those of weapons or basic attacks.
This should be fixed in the next release.
