### ISSUE TITLE
Accessories don't seem to be able to be equipped in Foundry V12

### ISSUE THREAD

**Issue by Dex10k** [League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima#139]
An Accessory added into the Character sheet doesn't seem to be able to be equipped
This was on Version 12 of foundry, I created a sapphire amulet giving it the frost resistance passive effect, and wasn't able to equip it onto the player.

**Comment by spyrella** [comment]
I also cannot reproduce this issue, what version of projectfu are you using?

**Comment by Dex10k** [comment]
I haven't encountered it again since foundry updated so I think its solved. However I forgot to mark down what the version of projectfu or Foundry were at the time.
I believe it was the most recent version of projectfu on July 9th but I'm uncertain.
