### ISSUE TITLE
Need to add journal ownership for V12 for study rolls

### ISSUE THREAD

**Issue by 4m2c4bl3** [League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima#140]
https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima/blob/337b6ab4a9af08eed6c0c3051ff3f914f58bcc2e/module/helpers/study-roll.mjs#L394C3-L394C13

Creating journal entries in v12 need an ownership property that works the same way permissions have in the past. Without it the GM needs to go manually give users permission after each study roll, as it gets reset.

**Comment by spyrella** [comment]
[#feat](https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima/blob/91e7e9b1ca00eaf72b469925681c988ffaca644f/module/helpers/study-roll.mjs#L396)
Issue has been addressed, fix will be available in next alpha release.

**Comment by 4m2c4bl3** [comment]
thanks!!
