### ISSUE TITLE
Correct attributes for spells not being assigned for display

### ISSUE THREAD

**Issue by 4m2c4bl3** [League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima#143]
When assigning attributes there seem to be two places the values can be set. in FUItem.system.accuracy.attributes.(primary|secondary), and also in FuItem.system.rollInfo.attributes.(primary|secondary). 

The value from the dropdown selection correctly is assigned to the rollInfo, so the spell works while rolling. But the values in accuracy don't seem to be properly set, so the display of what attributes are selected is incorrect in the character info.

I don't know why there are two places it can be found, but I assume if you just change attackAttributes in getSpellDisplayData to use the data from rollInfo it will be solved?

![image](https://github.com/user-attachments/assets/8cc47b98-46c5-4a19-9c5e-8df92b7cf302)
![image](https://github.com/user-attachments/assets/5cfd7087-f5fe-40fd-81ae-ba5ef91bd0d1)
![image](https://github.com/user-attachments/assets/f2775712-88bf-4ac8-8468-edbf3a9575f2)

**Comment by spyrella** [comment]
![image](https://github.com/user-attachments/assets/47df2c47-c5a5-48e1-ba66-58dcdbfe4e80)
My bad,
Spells uses
check.primary = item.system.rollInfo.attributes.primary.value;
check.secondary = item.system.rollInfo.attributes.secondary.value;

Weapons uses
check.primary = item.system.attributes.primary.value;
check.secondary = item.system.attributes.secondary.value;

Fixed the display issue, it should roll and display the correct die in the next alpha release

**Comment by 4m2c4bl3** [comment]
thank you!
