### ISSUE TITLE
Active Character for absent User

### ISSUE THREAD

**Issue by lanastara** [League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima#164]
**User Story:**
As a gm, it would be nice if there was a way to set the active characters instead of them being auto calculated using the active players.

**User Examples:**
If one of my players is absent and another player or the party as a whole takes over then there is currently no way of auto calculating exp using the meta-currency tracker.
According to the rules p.143 an absent character should be treated like any other character for xp but currenly they are ignored.

Version: 2.4.0-alpha.28

**Comment by Shourn** [comment]
Hi,
it should already be possible to override the active state of a player/character by clicking on the small "checkmark" icons in the active column of the meta-currency tracker.
Please do get back to us, if it isn't working for you.

**Comment by lanastara** [comment]
@Shourn Only the already active characters show up in the list so I can only remove active characters not add them

**Comment by Shourn** [comment]
No worries, happy to help.
