### ISSUE TITLE
Barrier Spell adds 12 def instead of sets def to 12

### ISSUE THREAD

**Issue by LitroTheDragon** [League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima#181]
Very simple. The temp effect for the Barrier spell has its Attribute Key set as "system.derived.def.bonus" instead of "system.derived.def.value" so it adds 12 Def to the player instead of setting the Def to 12.

**Comment by spyrella** [comment]
I applied the fixes, it'll be available in the next update V2.4.5
