### ISSUE TITLE
Quality label on Spell instead of Opportunity

### ISSUE THREAD

**Issue by FriendComputer0258** [League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima#55]
![Screenshot 2024-02-04 155557](https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima/assets/79923759/299a2c16-f247-4798-991a-82a5ce0d2634)
Small issue to report- I noticed in the chatlog prompt for spells the Opportunity field displays an item Quality field.  Guessing this is because the spells use the item template.  

Cosmetic issue but wanted to pass it along.

**Comment by spyrella** [comment]
Hey there, we're current in the process of revamping the chat roll infrastructure, 

![image](https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima/assets/16845165/bda8230f-9b9e-4bd9-a8c9-52d0e494c4ff)

Fixes would be available in the next update, thank you for the bug report!

**Comment by Shourn** [comment]
Yeah, that's probably on me. Internally "opportunity" is saved in the "quality" field and I forgot to adjust the display in that regard.

**Comment by FriendComputer0258** [comment]
Awesome!  Love the work everyone's put into this!

**Comment by Shourn** [comment]
Fixed in #56
