### ISSUE TITLE
Dual Shields don't benefit from Weapon Category Accuracy bonuses.

### ISSUE THREAD

**Issue by Cosmic-Cocoa** [League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima#73]
**Bug Description:**
Dual Shield Equipment does not benefit from active effects that grant an accuracy bonus to specific weapon categories.

**Steps to Reproduce:**
1. Add a Dual Shield in the Brawling category to the equipment of a character.
2. Add an active effect granting a bonus to the system.bonuses.accuracy.brawling attribute key.
3. Make an attack with the shield.

**Expected behavior:**
I expected there to be a +4 bonus to the Twin Shield's accuracy check.
Basically, I figured it would work just like it does if you add a bonus to the system.bonuses.accuracy.accuracyCheck attribute key.

**Attachments (if applicable):**
![shieldItem](https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima/assets/78349628/ef629fcf-781b-4f05-b6ec-262fc329d9e5)

![activeAccuracyEffect](https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima/assets/78349628/7fde8a35-034b-4f1d-9a07-472135f98861)

![attackRoll](https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima/assets/78349628/28b2da53-3f40-4915-86b2-c69946801ae6)

**Comment by spyrella** [comment]
Sorry, late too this issue. 

Trying to wrap my head around where your problem is stemming from, I think it was perhaps fixed in the dev version:
![image](https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima/assets/16845165/18d69081-4f89-4494-b640-af4350136891)

**Comment by Cosmic-Cocoa** [comment]
No worries at all. 

And sweet! In the game I'm playing in we just added the modifier in the item itself as a work around. We absolutely love the implementation in Foundry so I wanted to report it in case it was helpful to you guys.
