### ISSUE TITLE
Windows content incorrect padding

### ISSUE THREAD

**Issue by L4D15** [League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima#96]
**Bug Description:**
Many Foundry windows have lost their padding, making their content not leaving some space with the window border. It's not preventing the system to be usable but is visually unpleasant and gives a feel of "unfinished".

I have no modules active (in the screen they are checked but not activated, because I found the error when opening that window to activate the modules).

**Steps to Reproduce:**
1. Open any Foundry window, like Settings, or any popup.

**Expected behavior:**
There should be some spacing between the window border and the content.

**Attachments (if applicable):**
![Captura de pantalla 2024-03-19 a las 11 54 19](https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima/assets/2948600/1e98d63e-28c5-4157-992f-5fb4a61fbe5d)

**Comment by spyrella** [comment]
This will be addressed in V2.3.4, sorry about that.
![image](https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima/assets/16845165/3e586a84-504a-47b8-9240-6453bc974050)
